import type { CompanyRecord, OpportunityRecord } from '@/lib/types';

export const sampleCompanies: CompanyRecord[] = [
  {
    id: 'company-1',
    name: 'Pirimid Fintech',
    tier: 2,
    category: 'Fintech',
    location: 'Ahmedabad',
    website: 'https://pirimidtech.com',
    careers_url: 'https://pirimidtech.com/careers/',
    linkedin_url: 'https://www.linkedin.com/company/pirimid-fintech/',
    company_size: '51-200',
    ai_focus: 'Fraud detection and risk analytics',
    funding_stage: 'Series A',
    priority_base_score: 78,
    google_alert_set: true,
    li_alert_set: true,
    career_page_watched: true,
    last_careers_hash: 'sample-hash-1',
    last_checked: new Date().toISOString(),
    notes: 'High priority AI/ML watcher',
    created_at: new Date().toISOString(),
  },
  {
    id: 'company-2',
    name: 'GIFT City Data Labs',
    tier: 3,
    category: 'Analytics',
    location: 'GIFT City',
    website: 'https://example.com',
    careers_url: 'https://example.com/careers',
    linkedin_url: 'https://www.linkedin.com/',
    company_size: '11-50',
    ai_focus: 'Applied AI products',
    funding_stage: 'Seed',
    priority_base_score: 74,
    google_alert_set: false,
    li_alert_set: false,
    career_page_watched: false,
    last_careers_hash: null,
    last_checked: null,
    notes: 'Watch for proactive outreach',
    created_at: new Date().toISOString(),
  },
  {
    id: 'company-3',
    name: 'Gandhinagar Vision Systems',
    tier: 5,
    category: 'Computer Vision',
    location: 'Gandhinagar',
    website: 'https://example.com',
    careers_url: 'https://example.com/jobs',
    linkedin_url: 'https://www.linkedin.com/',
    company_size: '51-200',
    ai_focus: 'Computer vision and OCR',
    funding_stage: 'Bootstrapped',
    priority_base_score: 68,
    google_alert_set: false,
    li_alert_set: false,
    career_page_watched: true,
    last_careers_hash: null,
    last_checked: null,
    notes: 'No recent jobs posted',
    created_at: new Date().toISOString(),
  },
];

export const sampleOpportunities: OpportunityRecord[] = [
  {
    id: 'opp-1',
    company_name: 'Pirimid Fintech',
    role_title: 'ML Engineer',
    location: 'Ahmedabad',
    source: 'career_page',
    signal_type: 'early',
    apply_url: 'https://pirimidtech.com/careers/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 88,
    freshness_score: 35,
    raw_data: { sample: true },
    status: 'new',
    found_at: new Date(Date.now() - 12 * 60000).toISOString(),
    applied_at: null,
    follow_up_date: null,
    notes: 'Career page changed',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-2',
    company_name: 'GIFT City Data Labs',
    role_title: 'Data Scientist',
    location: 'GIFT City',
    source: 'naukri',
    signal_type: 'normal',
    apply_url: 'https://example.com/apply',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 76,
    freshness_score: 25,
    raw_data: { sample: true },
    status: 'new',
    found_at: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    applied_at: null,
    follow_up_date: null,
    notes: 'Fresh board hit',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-3',
    company_name: 'Gandhinagar Vision Systems',
    role_title: 'Applied AI Developer',
    location: 'Gandhinagar',
    source: 'google_alert',
    signal_type: 'proactive',
    apply_url: 'https://example.com',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 52,
    freshness_score: 15,
    raw_data: { sample: true },
    status: 'new',
    found_at: new Date(Date.now() - 26 * 60 * 60000).toISOString(),
    applied_at: null,
    follow_up_date: null,
    notes: 'Signal only',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-4',
    company_name: 'Sandbox Labs',
    role_title: 'Software Engineer',
    location: 'Ahmedabad',
    source: 'indeed',
    signal_type: 'normal',
    apply_url: 'https://example.com',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 34,
    freshness_score: 5,
    raw_data: { sample: true },
    status: 'applied',
    found_at: new Date(Date.now() - 3 * 24 * 60 * 60000).toISOString(),
    applied_at: new Date(Date.now() - 2 * 24 * 60 * 60000).toISOString(),
    follow_up_date: null,
    notes: 'Applied already',
    is_duplicate: false,
    duplicate_of: null,
  },
];
