import type { Company, Opportunity } from '@/lib/types';

const now = Date.now();

export const sampleCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'Pirimid Fintech',
    tier: 2,
    category: 'Fintech',
    location: 'Ahmedabad',
    website: 'https://pirimidtech.com',
    careers_url: 'https://pirimidtech.com/careers/',
    linkedin_url: 'https://www.linkedin.com/company/pirimid-fintech',
    company_size: '51-200',
    ai_focus: 'Fraud detection and risk analytics',
    funding_stage: 'Growth',
    priority_base_score: 78,
    google_alert_set: true,
    li_alert_set: false,
    career_page_watched: true,
    last_careers_hash: 'abc123',
    last_checked: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
    notes: 'Strong ML hiring signal.',
    created_at: new Date(now - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'company-2',
    name: 'Atlan',
    tier: 1,
    category: 'Data infrastructure',
    location: 'GIFT City',
    website: 'https://atlan.com',
    careers_url: 'https://atlan.com/careers',
    linkedin_url: 'https://www.linkedin.com/company/atlanhq',
    company_size: '201-500',
    ai_focus: 'Data catalog and AI ops',
    funding_stage: 'Series C',
    priority_base_score: 84,
    google_alert_set: true,
    li_alert_set: true,
    career_page_watched: true,
    last_careers_hash: 'def456',
    last_checked: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
    notes: 'Monitor for platform ML roles.',
    created_at: new Date(now - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'company-3',
    name: 'HDFC Bank',
    tier: 1,
    category: 'Banking',
    location: 'Gandhinagar',
    website: 'https://www.hdfcbank.com',
    careers_url: 'https://www.hdfcbank.com/careers',
    linkedin_url: 'https://www.linkedin.com/company/hdfc-bank',
    company_size: '10k+',
    ai_focus: 'Risk, personalization, automation',
    funding_stage: null,
    priority_base_score: 65,
    google_alert_set: false,
    li_alert_set: false,
    career_page_watched: true,
    last_careers_hash: null,
    last_checked: null,
    notes: 'Watch for internal AI transformation hiring.',
    created_at: new Date(now - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'company-4',
    name: 'Razorpay',
    tier: 1,
    category: 'Payments',
    location: 'Bengaluru / Ahmedabad remote',
    website: 'https://razorpay.com',
    careers_url: 'https://razorpay.com/jobs/',
    linkedin_url: 'https://www.linkedin.com/company/razorpay',
    company_size: '1000+',
    ai_focus: 'Payments intelligence',
    funding_stage: 'Late stage',
    priority_base_score: 76,
    google_alert_set: true,
    li_alert_set: true,
    career_page_watched: false,
    last_careers_hash: null,
    last_checked: null,
    notes: 'Potential proactive target.',
    created_at: new Date(now - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const sampleOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    company_name: 'Pirimid Fintech',
    role_title: 'ML Engineer',
    location: 'Ahmedabad',
    source: 'career_page',
    signal_type: 'early',
    apply_url: 'https://pirimidtech.com/careers/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 88,
    freshness_score: 35,
    raw_data: { page_hash: 'abc123' },
    status: 'new',
    found_at: new Date(now - 12 * 60 * 1000).toISOString(),
    applied_at: null,
    follow_up_date: null,
    notes: 'Career page changed this morning.',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-2',
    company_name: 'Atlan',
    role_title: 'Data Scientist',
    location: 'GIFT City',
    source: 'linkedin_email',
    signal_type: 'normal',
    apply_url: 'https://www.linkedin.com/jobs/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 79,
    freshness_score: 25,
    raw_data: { alert: 'linkedin_email' },
    status: 'applied',
    found_at: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    applied_at: new Date(now - 4 * 60 * 60 * 1000).toISOString(),
    follow_up_date: null,
    notes: 'Applied via link in alert.',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-3',
    company_name: 'HDFC Bank',
    role_title: 'AI Engineer',
    location: 'Gandhinagar',
    source: 'naukri',
    signal_type: 'normal',
    apply_url: 'https://www.naukri.com/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 67,
    freshness_score: 25,
    raw_data: { keyword: 'AI engineer' },
    status: 'new',
    found_at: new Date(now - 15 * 60 * 60 * 1000).toISOString(),
    applied_at: null,
    follow_up_date: null,
    notes: 'Worth monitoring.',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-4',
    company_name: 'Razorpay',
    role_title: 'Applied AI Developer',
    location: 'Remote',
    source: 'google_search',
    signal_type: 'proactive',
    apply_url: 'https://razorpay.com/jobs/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 54,
    freshness_score: 20,
    raw_data: { query: 'AI hiring' },
    status: 'followed_up',
    found_at: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    applied_at: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
    follow_up_date: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    notes: 'Proactive outreach drafted.',
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-5',
    company_name: 'Nexus Ventures',
    role_title: 'GenAI Research Intern',
    location: 'Ahmedabad',
    source: 'wellfound',
    signal_type: 'normal',
    apply_url: 'https://wellfound.com/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 39,
    freshness_score: 15,
    raw_data: { source_url: 'wellfound' },
    status: 'new',
    found_at: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    applied_at: null,
    follow_up_date: null,
    notes: null,
    is_duplicate: false,
    duplicate_of: null,
  },
  {
    id: 'opp-6',
    company_name: 'Signal Labs',
    role_title: 'Computer Vision Engineer',
    location: 'Ahmedabad',
    source: 'indeed',
    signal_type: 'normal',
    apply_url: 'https://in.indeed.com/',
    contact_name: null,
    contact_email: null,
    contact_linkedin: null,
    priority_score: 31,
    freshness_score: 10,
    raw_data: { source_url: 'indeed' },
    status: 'rejected',
    found_at: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applied_at: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    follow_up_date: null,
    notes: 'Archived.',
    is_duplicate: false,
    duplicate_of: null,
  },
];

export function fallbackTrackedCompanies() {
  return sampleCompanies.map((company) => {
    const latest = sampleOpportunities
      .filter((opportunity) => opportunity.company_name === company.name)
      .sort((a, b) => b.found_at.localeCompare(a.found_at))[0];

    return {
      ...company,
      last_signal: latest ? `${latest.source} · ${latest.role_title}` : 'No signal yet',
      last_signal_score: latest?.priority_score ?? company.priority_base_score ?? 0,
    };
  });
}
